#!/usr/bin/env bash
# Displays the content of the file /etc/passwd, using the while loop + IFS
# print format: "The user [USERNAME] is a part of the [GROUP_ID] gng, lives in [HOME_DIRECTORY] and rides [COMMAND/SHELL]. [USER_ID]'s place id protected by the passcode [PASSWORD], more info about the user here: [USER ID INFO]

while IFS=: read -r f1 f2 f3 f4 f5 f6 f7
do
	echo "The user $f1 is part of the $f4 gang, lives in the $f6 and rides $f7. $f3's place is protected by passcode $f2, more info about the user here: $f5"
done < /etc/passwd
