#!/usr/bin/env bash
# Displays the content of the file /etc/passwd
# only displays username, user ID and home directory path for user.

while read -r passwd
  do
    echo "$passwd" | cut -d ":" -f1,3,6
done < '/etc/passwd'
