#!/usr/bin/env bash
# Displays "Best School" but displays "Hi" on the 9th iteration

num=1

while [ $num -le 10 ]
do
  echo "Best School"
  if [ $num -eq 9 ]
  then
    echo "Hi"
  fi
  ((num++))
done
