#!/usr/bin/env bash
# gives information about the school file
# if file exist print "school file exists"
#	and if it is empty print "school file is empty"
#	if not print "school file is not empty"
#	if it is a regular file  print "school is a regular file"
# if not print "school file does not exist"

if [ -e school ]
  then
    echo "school file exists"
    if [ -s school ]
      then
        echo "school file is not empty"
    else
      echo "school file is empty"
    fi
    if [ -f school ]
      then
        echo "school is a regular file"
    fi
else
  echo "school file does not exist"
fi
